### PR TITLE
Summarize `kube::Error` changes

### PR DESCRIPTION
**Pull request by kazk**
## Motivation

Make the changelog less overwhelming for average users (https://github.com/kube-rs/kube-rs/issues/709#issuecomment-969250313)

## Solution

Summarized the changes to `kube::Error` and moved the original in `<details>`.

### CODE REVIEW

**Review by clux — APPROVED** [review]
ah, nice use of a collapsible comment :-)

**Comment by clux** [comment]
Sounds like we are good for a minor release. Want me to do one?

**Comment by clux** [comment]
(Waiting for rustls also seems sensible here, but no problem to do another minor.)

**Comment by kazk** [comment]
Yeah, I think we can cut a new release. I can remove `Error::RustlsTls` from the changelog later.

> * Added `Error::RustlsTls(kube::client::RustlsTlsError)` (errors from `rustls-tls` feature) - #704

**Comment by clux** [comment]
I can remove that one line before release. Need to commit to master anyway.

**Comment by clux** [comment]
Ok, all done. 0.64.0 is out.
https://github.com/kube-rs/kube-rs/commit/f9bfe11d6f481f2ab64126cf38f6063cd6a03f73 is the removed line.

Thanks again for all the great error work this release!

**Pull request merged**
