### PR TITLE
bump k8s-openapi 0.13.0 and revert option unpacking - fixes #581

### LINKED ISSUE #581: Api::replace can fail to unset list values with k8s-openapi 0.12
The `Option` removal change had some unfortunate consequences.
See https://github.com/Arnavion/k8s-openapi/issues/103
Keeping this as a tracking issue in here, because we are still doing some releases.

You probably won't notice this if you are using small patches in your mutations, but be aware that you might not be able to unset certain values with `Api::replace`

### PR DESCRIPTION
**Pull request by clux**
reverts unpacking from #531 while bumping k8s-openapi for https://github.com/Arnavion/k8s-openapi/releases/tag/v0.13.0

### CODE REVIEW

**Comment by clux** [comment]
Cargo-deny on `tar`:
> Solution: No safe upgrade is available! :ok_man:

**Comment by lfrancke** [comment]
I'll open a PR to fix the CI (cargo deny). That was my fault. An advisory shouldn't block a PR.

**Comment by clux** [comment]
@lfrancke It's not actually blocking it, and we're not using it as a required status, so it's OK. It's just a bit annoying that advisories can be released without fixes. We got an issue about the same thing which was reasonable.

**Comment by lfrancke** [comment]
Okay. In theory I thought github actions is set up to ignore errors from the advisories run but for some reason it doesn't.
We just hit the same today and fixed it like this.: https://github.com/stackabletech/agent-integration-tests/pull/53/files

I don't understand why the original/current version doesn't work but I'm happy to create a PR if you like.

**Comment by clux** [comment]
Yeah, very happy to take a PR for only doing the license ban on PR if you have time. The red cross will show up in places and will be a bit annoying. The issues for advisories are probably sufficient.

**Pull request merged**
