### PR TITLE
Add support for EC private keys

### PR DESCRIPTION
**Pull request by farcaller**
## Motivation

Allows to use kube-rs with e.g. k3s and k3d default installs that use the Sec1 private keys.

## Solution

This depends on
- [x] https://github.com/rustls/pemfile/pull/5
- [x] https://github.com/rustls/rustls/pull/998
- [x] waiting for the rustls release to catch up

### CODE REVIEW

**Comment by farcaller** [comment]
Note that this PR alone won't be enough to make k3s work as the default kubeconfig uses IP addresses. The relevant feature request is here: https://github.com/briansmith/webpki/issues/54.

**Comment by clux** [comment]
Realised that the jobs here never ran, hence the sudden activity. The red deny :x: looks like what was fixed in master.

**Comment by farcaller** [comment]
The deps caught up, this is now ready for review.

**Comment by clux** [comment]
CI test failure remaining on cargo-deny: hyper-rustls brings in an older version of `rustls-pemfile`.
Looks like this will be resolved by https://github.com/rustls/hyper-rustls/pull/165

**Comment by farcaller** [comment]
I can’t see what the CI failed on, any advice?

**Comment by clux** [comment]
Can confirm that this works on `k3d` now (with some user work to bypass the out-of-the-box case):

Earlier error:
- `Error: rustls tls error: identity PEM is missing a private key: the key must be PKCS8 or RSA/PKCS1`

New bypassable error:
- `Error: failed to perform initial object list: HyperError: error trying to connect: invalid dnsname`

Bypass: #153 (add `localhost` entry to /etc/hosts and change the kube/config cluster.server url to use `localhost`)

@farcaller : it nothing important all the important things pass. the failing check is [`cargo-deny`](https://github.com/EmbarkStudios/cargo-deny) which you can run locally with `make deny` - it's just trying to limit multiple versions of dependencies in the dependency tree. It's possible we can put a bypass for it (this is an important fix after all), but it would be nicer to wait for `hypertls-rustls` to make a release with the updated pemfile dep.

**Comment by clux** [comment]
We will add an override file for this after making a 0.69 release (today/tomorrow), and merge this right after. then hopefully the ecosystem acquires internal consistency in the mean time (or else 0.70 release will be released with the override).

in either case don't want to delay this too much, but want to **try to** keep the set of dependencies consistent

**Review by clux — APPROVED** [review]

**Comment by clux** [comment]
Override added so all checks passing now. Merging.

Thanks again!

**Pull request merged**
