### PR TITLE
Expose shortnames of `CustomResource` derive

### PR DESCRIPTION
**Pull request by teozkr**
Fixes https://github.com/stackabletech/issues/issues/93

Discussion at https://discord.com/channels/500028886025895936/685161813675212899/879789729061679204

/cc @maltesander, @lfrancke

### CODE REVIEW

**Review by clux — APPROVED** [review]
Looks great!

**Comment by teozkr** [comment]
Oh right, need to start remembering to --signoff.. :P

**Comment by lfrancke** [comment]
That was fast! I didn't even have time to look at it :)
Thank you!

I had something started as well but yours is much better.
There are a few other things that are not exposed yet IIRC...might make sense for completeness sake to do those as well.

**Comment by clux** [comment]
Released in 0.61.0.

**Pull request merged**
