### PR TITLE
Serialize and Deserialize implementations for ApiResource

### PR DESCRIPTION
**Pull request by vapourismo**
Would be great to have these very convenient traits implemented for `ApiResource`.

### CODE REVIEW

**Comment by clux** [comment]
Hey there. Thanks for this! I think this makes complete sense to include.

__I will get around to__ merging this __before the next release__, just trying to sort out a few admin things with this repo right now.

**Review by teozkr — APPROVED** [review]
Nit: it's a bit redundant to export both `group`+`version` and `api_version`

**Comment by clux** [comment]
Sorry, we added a DCO check in the mean time before merging. If you're able to fix I'll merge, otherwise I'll do something similar in master.

**Comment by vapourismo** [comment]
I'll fix it.

**Comment by clux** [comment]
Awesome, TYVM! I'll put it in for a release tonight along with the k8s-openapi pr.

**Pull request merged**
