### PR TITLE
remove in_current_span

### PR DESCRIPTION
**Pull request by Sherlock-Holo**
## Motivation

Currently, the `in_current_span` will break jaeger, it will make a lot of spans in one result, like 
image
image

the jaeger reports all of the `reconciling object` has a invalid parent id
image

This PR will make the trace works.

## Solution

remove the `in_current_span` will make jaeger result become normal, like
image

but this will make the `reconciling object` span lost, I don't know how to add `reconciling object` back but don't break the jaeger result

### CODE REVIEW

**Comment by teozkr** [comment]
Need to test this in more detail to understand what's going on, but I don't think removing the span connection entirely is the long-term solution. That said, this is still a useful bug report!

**Comment by clux** [comment]
Hm. Interesting. I believe this was added in #600 to explicitly attach the two. Weird that one is not found, last I checked tempo rendered this fine (but will check again). Do you mind sharing how you are creating your root span / instrumenting your `reconcile` fn?

**Comment by Sherlock-Holo** [comment]
> Hm. Interesting. I appreciate the detailed screenshots here to show what is going on, and for reporting this. I believe this was added in #600 to explicitly attach the two. Weird that one is not found, last I checked Tempo rendered this fine (but can check again). Do you mind sharing how you are creating your root span / instrumenting your `reconcile` fn?

my reconcile async function is https://github.com/Sherlock-Holo/ddns/blob/0b57fa72934f77a5f8559ce6f5bf8d1c898e4b3f/src/reconcile.rs#L69

**Comment by clux** [comment]
Ah, this makes sense now. You are nesting every reconciliation onto the root span in `run_controller`: https://github.com/Sherlock-Holo/ddns/blob/0b57fa72934f77a5f8559ce6f5bf8d1c898e4b3f/src/control.rs#L14-L15

This is probably not ideal (and can probably be fixed by removing that instrument) but it's also not something we should be allowing. Each reconciliation is meant to be its own unit of work, and should have its own span so it's probably wrong for us to try to attempt to nest these regardless.

I am :+1:  with merging this.

**Comment by teozkr** [comment]
Hm, you'd think that the `#[tracing::instrument]` on the `reconcile` would override the span that we provide in that case. Have we actually confirmed that removing the `instrument` fixes it as well?

**Comment by teozkr** [comment]
Removing the `in_current_span` means that the framework-created span is not applied, which isn't great either... :/

**Comment by clux** [comment]
> Hm, you'd think that the `#[tracing::instrument]` on the `reconcile` would override the span that we provide in that case. Have we actually confirmed that removing the `instrument` fixes it as well?

I'll look at verifying behaviour later in the evening today with tempo. Pretty sure I can reproduce it there via controller-rs (by putting root instrument on main or manager) and seeing how it looks.

The only potential reason I can see for having `in_current_span` in `Controller::run` is if we want requeues to be part of the same trace, because the error_policy gets run in scope with our created span anyway.

**Comment by teozkr** [comment]
Without it the reconcile (whether the initial or a requeue) won't run in the span at all.

To compare, here's the log output of controller-rs (switching from the JSON formatter to the plain text one) on the current `master`:


>Running `target/debug/controller`
>2021-12-08T09:53:51.754302Z  INFO reconciling object{object.ref=Foo.v1.clux.dev/good.default object.reason=object updated}:reconcile{foo=Foo { metadata: ObjectMeta { annotations: Some({"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"clux.dev/v1\",\"kind\":\"Foo\",\"metadata\":{\"annotations\":{},\"name\":\"good\",\"namespace\":\"default\"},\"spec\":{\"info\":\"good person, good instance\",\"name\":\"good foo\"}}\n"}), cluster_name: None, creation_timestamp: Some(Time(2021-12-08T09:51:33Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(1), labels: None, managed_fields: Some([ManagedFieldsEntry { api_version: Some("clux.dev/v1"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object({"f:status": Object({"f:is_bad": Object({})})}))), manager: Some("cntrlr"), operation: Some("Apply"), subresource: None, time: Some(Time(2021-12-08T09:51:33Z)) }, ManagedFieldsEntry { api_version: Some("clux.dev/v1"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object({"f:metadata": Object({"f:annotations": Object({".": Object({}), "f:kubectl.kubernetes.io/last-applied-configuration": Object({})})}), "f:spec": Object({".": Object({}), "f:info": Object({}), "f:name": Object({})})}))), manager: Some("kubectl-client-side-apply"), operation: Some("Update"), subresource: None, time: Some(Time(2021-12-08T09:51:33Z)) }]), name: Some("good"), namespace: Some("default"), owner_references: None, resource_version: Some("3502"), self_link: None, uid: Some("bd8054aa-6ad6-426a-8713-1362fa75b9e5") }, spec: FooSpec { name: "good foo", info: "good person, good instance" }, status: Some(FooStatus { is_bad: false }) } trace_id=00000000000000000000000000000000}: controller::manager: Reconciled Foo "good" in default

And here's the log output with this patch applied:

>Running `target/debug/controller`
>2021-12-08T09:54:45.469542Z  INFO reconcile{foo=Foo { metadata: ObjectMeta { annotations: Some({"kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"clux.dev/v1\",\"kind\":\"Foo\",\"metadata\":{\"annotations\":{},\"name\":\"good\",\"namespace\":\"default\"},\"spec\":{\"info\":\"good person, good instance\",\"name\":\"good foo\"}}\n"}), cluster_name: None, creation_timestamp: Some(Time(2021-12-08T09:51:33Z)), deletion_grace_period_seconds: None, deletion_timestamp: None, finalizers: None, generate_name: None, generation: Some(1), labels: None, managed_fields: Some([ManagedFieldsEntry { api_version: Some("clux.dev/v1"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object({"f:status": Object({"f:is_bad": Object({})})}))), manager: Some("cntrlr"), operation: Some("Apply"), subresource: None, time: Some(Time(2021-12-08T09:51:33Z)) }, ManagedFieldsEntry { api_version: Some("clux.dev/v1"), fields_type: Some("FieldsV1"), fields_v1: Some(FieldsV1(Object({"f:metadata": Object({"f:annotations": Object({".": Object({}), "f:kubectl.kubernetes.io/last-applied-configuration": Object({})})}), "f:spec": Object({".": Object({}), "f:info": Object({}), "f:name": Object({})})}))), manager: Some("kubectl-client-side-apply"), operation: Some("Update"), subresource: None, time: Some(Time(2021-12-08T09:51:33Z)) }]), name: Some("good"), namespace: Some("default"), owner_references: None, resource_version: Some("3502"), self_link: None, uid: Some("bd8054aa-6ad6-426a-8713-1362fa75b9e5") }, spec: FooSpec { name: "good foo", info: "good person, good instance" }, status: Some(FooStatus { is_bad: false }) } trace_id=00000000000000000000000000000000}: controller::manager: Reconciled Foo "good" in default

Note how the log message doesn't have the framework-supplied span at all in the second case.

**Comment by clux** [comment]
Checked on Tempo today:

with the change (only user spans):
Screenshot from 2021-12-09 23-02-46

without the change (we get the framework created span):
Screenshot from 2021-12-09 23-05-21

(confirming teo's comment)

furthermore, if we miss that framework span, and have an error from the reconciler, that root span is the only way we can see it in the trace:
Screenshot from 2021-12-09 23-16-36

so removing the linking is probably the wrong choice after all.

unfortunately, i am not able to reproduce the big-combined trace that is seen here by adding more `#[instrument]` calls above, so maybe that's something to with how the particular instrumentation is buffering for jaeger.

@Sherlock-Holo are you able to try without your [root instrument](https://github.com/Sherlock-Holo/ddns/blob/0b57fa72934f77a5f8559ce6f5bf8d1c898e4b3f/src/control.rs#L14-L15) in your codebase?

**Comment by Sherlock-Holo** [comment]
@clux after remove the `#[instrument]` from the `pub async fn run_controller()`, the jeager becomes normal

image

Is there a good way to keep the framework span, and won't be broken if the user writes codes like my `pub async fn run_controller()`?

for now, we have to notice user the framework has its own span, be careful when using the `#[instrument]` when start the controller, or remove the `in_current_span` to make sure no one's jaeger become broken

**Comment by clux** [comment]
> @clux after remove the `#[instrument]` from the `pub async fn run_controller()`, the jeager becomes normal

Ah, that's at least good. Thanks for confirming.

> Is there a good way to keep the framework span, and won't be broken if the user writes codes like my `pub async fn run_controller()`?
> 
> for now, we have to notice user the framework has its own span, be careful when using the `#[instrument]` when start the controller, or remove the `in_current_span` to make sure no one's jaeger become broken

In general, the common pattern is that the controller should start outside the framework, and have its state (reflector store e.g.) loaded into the framework (e.g. actix via Data. I don't imagine it is super useful to have instrumentation on something that is equivalent to `main`, so you might have to answer what you are trying to achieve with that. A global super-trace across the entire lifecycle of your app is effectively what you are asking for, and that's going to be pretty heavy on your collectors (and should look like what you are getting).

**Comment by Sherlock-Holo** [comment]
I think you are right, use the `#[instrument]` for `run_controller` is bad idea and we should avoid to do it :)

**Comment by teozkr** [comment]
Alright, closing this issue then.

**Pull request closed without merging**
